In [2]:
import numpy as np
a=[10,20,30,40]
type(a)


list

In [5]:
x=np.array(a)
print(x)


[10 20 30 40]


In [7]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [16]:
x=np.array([1,2,3,4],dtype=np.float32)
print(x)

[1. 2. 3. 4.]


In [18]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
x=np.zeros((4,4))
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [26]:
x=np.random.rand(2,5)
print(x)


[[0.98657928 0.57319365 0.34453901 0.20244371 0.48142846]
 [0.54345658 0.5030977  0.33300683 0.66434207 0.21923937]]


In [28]:
np.random.rand
np.random.randint(1,20,size=(3,3))

array([[12,  7,  1],
       [18,  3,  3],
       [ 6, 10,  6]])

In [30]:
np.random.randint
np.random.randn(2,5)


array([[-0.33526173, -1.89540379, -0.01371105,  2.32773228,  0.42949747],
       [ 0.34692469, -1.11519137, -0.26365893,  1.74895212, -0.11528786]])

In [32]:
np.random.randn
np.random.choice([2,3,4,7,8,10])

np.int64(4)

In [34]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [36]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [38]:
x=np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [40]:
np.eye
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [43]:
np.eye
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.eye
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
a=[10,20,30,40,50]
x=np.array(a)
print(x)


[10 20 30 40 50]


In [55]:
x.ndim

1

In [56]:
b=[1,2,3,4,5]
y=np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [57]:
y.ndim


2

In [58]:
y.shape

(2, 5)

In [59]:
y.size

10

In [60]:
a=np.array([3,6,9,12])
print(a)


[ 3  6  9 12]


In [62]:
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [63]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [64]:
x=np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
x.size

15

In [66]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [67]:
x=np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [68]:
y=x.reshape(3,5)
print(y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [69]:
z=np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [70]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [71]:
a=np.arange(1,10)
print(a)


[1 2 3 4 5 6 7 8 9]


In [72]:
a[2:6]


array([3, 4, 5, 6])

In [76]:
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
x[1,2]

np.int64(6)

In [78]:
x[1][2]

np.int64(6)

In [79]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [80]:
a=np.arange(1,6)
b=np.arange(6,11)
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [82]:
x=np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [85]:
x=np.hstack((a,b))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [87]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [89]:
np.concatenate((a,b))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [91]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [92]:
a=np.arange(10,21,2)
b=np.array([[2],[2]])
print(a)


[10 12 14 16 18 20]


In [93]:
print(b)

[[2]
 [2]]


In [94]:
z=a+b
print(z)


[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [95]:
a=np.arange(10,21,2)

In [96]:
a+2

array([12, 14, 16, 18, 20, 22])

In [97]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [98]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [99]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [100]:
a=np.ones((3,3))
b=np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [101]:
print(b)

[2]


In [102]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [103]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [104]:
a=np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [105]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [106]:
a-1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [107]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [108]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [109]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [112]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [111]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
a=np.arange(5,15,2)
print(a)

[ 5  7  9 11 13]


In [114]:
np.mean(a)

np.float64(9.0)

In [115]:
np.median(a)

np.float64(9.0)

In [116]:
np.std(a)

np.float64(2.8284271247461903)

In [117]:
a=np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [118]:
print(np.min(a,axis=0))


[1 3]


In [119]:
print(np.min(a,axis=1))

[1 3]


In [120]:
print(np.max(a,axis=1))

[6 4]


In [121]:
print(np.max(a,axis=0))

[4 6]


In [122]:
a=np.array([1,4,3,10,20])
x=np.sort(a,kind='mergesort')
print(x)

[ 1  3  4 10 20]


In [125]:
A= np.arange(0,9).reshape(3,3)

In [132]:
B=np.ones((3,3))

In [133]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [134]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [135]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [136]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])